config/routes.rb
Rails.application.routes.draw do
  # Это правило говорит: если пользователь заходит по адресу /, направь его в
  # контроллер users, действие index. Грубо говоря, на главной странице у нас
  # список юзеров.
  root 'users#index'

  # Ресурс пользователей
  resources :users

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  # Ресурс сессии (только три экшена :new, :create, :destroy)
  resource :session, only: [:new, :create, :destroy]

end

app/models/question.rb
# Модель вопроса.
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :user, presence: true
  validates :text, length: { maximum: 255 }, presence: true

end

app/controllers/questions_controller.rb
# Контроллер, управляющий вопросами. Действия:
#
# 1. Редактирует вопрос
# 2. Создает вопрос
# 3. Удаляет вопрос
#
class QuestionsController < ApplicationController
  # Инициализируем объект вопрос для экшенов кроме :edit, :update, :destroy
  before_action :load_question, only: [:edit, :update, :destroy]

  # Проверяем имеет ли юзер доступ к экшену для всей дествий, кроме задавания
  # вопроса, это действие может вызвать даже неавторизованный пользователь.
  before_action :authorize_user, except: [:create]

  # Действие edit будет отзываться по адресу /questions/:id/edit, например,
  # /questions/1/edit
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def edit
  end

  # Действие create будет отзываться при POST-запросе по адресу /questions из
  # формы нового вопроса, которая находится в шаблоне на странице
  # /questions/edit
  def create
    @question = Question.new(question_params)
    @question.author = current_user

    # Проверяем капчу вместе с сохранением вопроса. Если в капче была допущена
    # ошибка, она будет добавлена в ошибки @question.errors.
    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # вопроса, которая находится по адресу /questions/:id, например, /questions/1
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  # Действие destroy будет отзываться при DELETE-запросе со страницы
  # пользователя, которая находится по адресу /users/:id/show.
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def destroy
    # Перед тем, как удалять вопрос, сохраним пользователя, чтобы знать, куда
    # редиректить после удаления.
    user = @question.user

    # Удаляем вопрос
    @question.destroy

    # Отправляем пользователя на страницу адресата вопроса с сообщением
    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private

  # Если загруженный из базы вопрос не пренадлежит и текущему залогиненному
  # пользователю — посылаем его с помощью описанного в контроллере
  # ApplicationController метода reject_user.
  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Загружаем из базы запрошенный вопрос, находя его по params[:id].
  def load_question
    @question = Question.find(params[:id])
  end

  # Явно задаем список разрешенных параметров для модели Question. Мы говорим,
  # что у хэша params должен быть ключ :question. Значением этого ключа может
  # быть хэш с ключами: :user_id и :text. Другие ключи будут отброшены.
  def question_params
    # Защита от уязвимости: если текущий пользователь — адресат вопроса,
    # он может менять ответы на вопрос, ему доступно также поле :answer.
    if current_user.present? &&
        params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  private

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
      <% if @question.errors.any? %>
          <div class="form-errors">
            <ul>
              <% @question.errors.full_messages.each do |message| %>
                  <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, 'Вопрос', class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%# Простая авторизация - может ли текущий юзер править вопрос? %>
      <% if current_user.present? && current_user == @question.user %>
          <div class="form-field">
            <%= f.label :answer, 'Ответ', class: 'form-label' %>
            <%= f.text_area :answer, class: 'form-textarea' %>
          </div>
      <% end %>

      <%= recaptcha_tags unless current_user.present? %>

      <div class="form-action buffer-both">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        или
        <%= link_to "вернуться", user_path(@question.user) %>
      </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <%# Текст ответа, если он есть %>
    <% if question.answer.present? %>
        <div class="question-answer text-lead">
          <%= question.answer %>
        </div>
    <% end %>

    <%# Дата создания вопроса (отформатированная) %>
    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>

    <%# Добавляем автора вопроса%>
    <div class="question-date">
      <% if question.author.present? %>
        <%=  link_to 'От: ' + question.author.username, user_path(question.author) %>
      <% else %>
        <p>Автор не представился</p>
    </div>
    <% end %>
  </div>

  <%# Если адресат вопроса — текущий пользователь, он может редактировать вопрос %>
  <%# и отвечать на него %>
  <% if question.user == current_user %>
      <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
      <%# овтета на письмо, иначе — карандашик %>
      <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

      <div class="question-actions">
        <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
        <%= link_to fa_icon('trash-o'), question_path(question),
                    method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
      </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>