config/routes.rb
Rails.application.routes.draw do
  # Это правило говорит: если пользователь заходит по адресу /, направь его в
  # контроллер users, действие index. Грубо говоря, на главной странице у нас
  # список юзеров.
  root 'users#index'

  # Ресурс пользователей
  resources :users

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  # Ресурс сессии (только три экшена :new, :create, :destroy)
  resource :session, only: [:new, :create, :destroy]

end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  attr_accessor :password

  # параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, uniqueness: true, presence: true
  validates_email_format_of :email, :message => 'is not looking good'
  validates :username, uniqueness: true, presence: true, length: { in: 2..40 }, format: { with: /\A[a-zA-Z][a-zA-Z0-9-_]*\z/ }

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password
  before_validation :username_downcase

  def username_downcase
    username.downcase! if username.present?
  end

  def encrypt_password
    if self.password.present?
      # добавляем соль для усложнения пароля
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # создаем хэш пароля - уникальная строка, из которой невозможно восстановить
      # исходный пароль
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST
        ))
    end
  end

  # служебный метод, преобразующий бинарную строку в 16-ричный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  # медот для аутентификации пользователей
  def self.authenticate(email, password)
    user = find_by(email: email) # сначала находим пользователя по email

    # ВНИМАНИЕ: сравнивается только password_hash, а оригинальный пароль никогда
    # нигде не сохраняется!
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password,
    user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

end

app/controllers/users_controller.rb
# Контроллер, управляющий пользователями. Должен уметь:
#
#   1. Показывать страницу пользователя
#   2. Создавать новых пользователей
#   3. Позволять пользователю редактировать свою страницу
#
class UsersController < ApplicationController
  # Загружаем юзера из базы для экшенов кроме :index, :create, :new
  before_action :load_user, except: [:index, :create, :new]

  # Проверяем имеет ли юзер доступ к экшену, делаем это для всех действий, кроме
  # :index, :new, :create, :show — к этим действиям есть доступ у всех, даже у
  # тех, у кого вообще нет аккаунта на нашем сайте.
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  # Действие new будет отзываться по адресу /users/new
  def new
    # Если пользователь уже авторизован, ему не нужна новая учетная запись,
    # отправляем его на главную с сообщением.
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    # Иначе, создаем болванку нового пользователя.
    @user = User.new
  end

  # Действие create будет отзываться при POST-запросе по адресу /users из формы
  # нового пользователя, которая находится в шаблоне на странице /users/new.
  def create
    # Если пользователь уже авторизован, ему не нужна новая учетная запись,
    # отправляем его на главную с сообщением.
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    # Иначе, создаем нового пользователя с параметрами, которые нам предоставит
    # метод user_params.
    @user = User.new(user_params)

    # Пытаемся сохранить пользователя.
    if @user.save
      # Если удалось, отправляем пользователя на главную с сообщение, что
      # пользователь создан.
      redirect_to root_url, notice: 'Пользователь успешно зарегестрирован!'
      # Сразу же авторизуем пользователя
      session[:user_id] = @user.id
    else
      # Если не удалось по какой-то причине сохранить пользователя, то рисуем
      # (обратите внимание, это не редирект), страницу new с формой
      # пользователя, который у нас лежит в переменной @user. В этом объекте
      # содержатся ошибки валидации, которые выведет шаблон формы.
      render 'new'
    end
  end

  # Действие edit будет отзываться по адресу /users/:id/edit, например,
  # /users/1/edit
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def edit
  end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # пользователя, которая находится по адресу /users/:id, например,
  # /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def update
    # Аналогично create, мы получаем параметры нового (обновленного)
    # пользователя с помощью метода user_params, и пытаемся обновить @user с
    # этими значениями.
    if @user.update(user_params)
      # Если получилось, отправялем пользователя на его страницу с сообщением,
      # что пользователь успешно обновлен.
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      # Если не получилось, как и в create рисуем страницу редактирования
      # пользователя, на которой нам будет доступен объект @user, содержащий
      # информацию об ошибках валидации, которые отобразит форма.
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Аккаунт удален'
  end

  # Это действие отзывается, когда пользователь заходит по адресу /users/:id,
  # например /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def show
    # Достаем вопросы пользователя с помощью метода questions, который мы
    # объявили в модели User (has_many :questions), у результата возврата этого
    # метода вызываем метод order, который отсортирует вопросы по дате.
    @questions = @user.questions.order(created_at: :desc)

    # Для формы нового вопроса, которая есть у нас на странице пользователя,
    # создаем болванку вопроса, вызывая метод build у результата вызова метода
    # @user.questions.
    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  private

  # Если загруженный из базы юзер и текущий залогиненный не совпадают — посылаем
  # его с помощью описанного в контроллере ApplicationController метода
  # reject_user.
  def authorize_user
    reject_user unless @user == current_user
  end

  # Загружаем из базы запрошенного юзера, находя его по params[:id].
  def load_user
    @user ||= User.find params[:id]
  end

  # Явно задаем список разрешенных параметров для модели User. Мы говорим, что
  # у хэша params должен быть ключ :user. Значением этого ключа может быть хэш с
  # ключами: :email, :password, :password_confirmation, :name, :username и
  # :avatar_url. Другие ключи будут отброшены.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :color_background)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
        <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
        <%# в поле errors модели (в нашем случае @users). %>
        <% if @user.errors.any? %>
            <div class="form-errors">
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li class="form-error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%# С помощью методов label и text_field у объекта f мы создаем теги %>
        <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field">
          <%= f.label :username, class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <%# Поступаем аналогично для других полей %>
        <div class="form-field">
          <%= f.label 'Ваше имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'URL вашей аватарки', class: 'form-label' %>
          <%= f.text_field :avatar_url, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label 'Цвет фона', class: 'form-label' %>
          <%= f.color_field :color_background, class: 'form-text-field' %>
        </div>

        <div class="buffer-top-large buffer-bottom">
          Если не хотите менять пароль — оставьте эти поля пустыми!
        </div>

        <div class="form-field">
          <%= f.label :password, class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action buffer-top">
          <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
        </div>

        <div class="form-action buffer-top">
          <%= link_to 'Удалить аккаунт', user_path(@user), method: :delete,
              data: {confirm: 'Вы точно хотите удалить аккаунт?'}, class: 'button button-dark button-small'%>
        </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда посетитель захочет посмотреть список %>
<%# пользователей на странице /users (users#index) %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж четырьмя хелперами: %>
          <%# * link_to — генерирует ссылку %>
          <%# * image_tag — генерирует картинку %>
          <%# * user_avatar — достает из пользователя ссылку на картинку %>
          <%#   или подставляет дефолтную %>
          <%# * user_path(user) возвращает относительный путь страницы %>
          <%#   пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%# Страница для регистрации нового пользователя. %>

<%# Обратите внимание, что она очень похожа на страницу редактирования юзера, %>
<%# что позволяет в подобных случаях использовать один и тот же паршиал form %>
<%# в обоих страницах. %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for @user do |f| %>
        <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
        <%# в поле errors модели (в нашем случае @users). %>
        <% if @user.errors.any? %>
            <div class="form-errors">
              <ul>
                <% for message in @user.errors.full_messages %>
                    <li class="form-error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <%# С помощью методов label и text_field у объекта f мы создаем теги %>
        <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field">
          <%= f.label :email, 'Логин (email)', class: 'form-label' %>
          <%= f.text_field :email, class: 'form-text-field' %>
        </div>

        <%# Поступаем аналогично для других полей %>
        <div class="form-field">
          <%= f.label :username, 'Никнейм', class: 'form-label' %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :name, 'Имя', class: 'form-label' %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password, 'Пароль', class: 'form-label' %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
        </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/show.html.erb
<%# В шаблоне show мы пишем html-код для вывода внутреннго содержимого %>
<%# страницы пользователя, которая будет показана по адресу /users/1 %>

<%# Блок с информацией о пользователей %>
<div class="user-header text-center" style="background: <%= @user.color_background %>">
  <h1 class="title-medium">
    <%# Выводим имя пользователя %>
    <%= @user.name %>
  </h1>

  <%# Добавляем ссылку для редактирования пользователя, которая ведет на %>
  <%# страницу /users/:id/edit %>
  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%# Рисуем аватарку пользователя. Мы используем хелперы image_tag, %>
    <%# встроенный в rails, и наш user_avatar %>
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    <%# Выводим никнейм пользователя с символом «@» перед ним. %>
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%# Используем встроенный в rails хелпер link_to %>
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= sklonenie(@questions_count, 'вопрос', 'вопроса', 'вопросов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= sklonenie(@answers_count, 'ответ', 'ответа', 'ответов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= sklonenie(@unanswered_count, 'безответный', 'безответных', 'безответных') %></p>
    </div>
  </div>
</div>

<%# Блок с формой для задавания пользователю вопроса %>
<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
      <%# Мы используем хелпер form_for, принимающий на вход блок erb-кода, %>
      <%# в котором доступна переменная f, содержащая так называемый form %>
      <%# builder, с помощью которого можно делать поля формы для нового %>
      <%# вопроса. %>
      <%= form_for @new_question do |f| %>
          <%# С помощью объекта для создания полей формы, связанной с моделью %>
          <%# @new_question Мы создаем инпуты с нужными полями для формы, %>
          <%# значения будут подставлены rails автоматически. %>
          <%= f.hidden_field :user_id %>

          <div class="form-field">
            <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
            <%= f.text_area :text, class: 'form-textarea' %>
          </div>

          <%= recaptcha_tags size: 'compact' unless current_user.present? %>

          <div class="form-action">
            <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
          </div>
      <% end %>
  </div>
</div>

<%# Блок со списком вопросов к пользователю %>
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <%# Обратите внимание, как мы делаем цикл по всем вопросам, точно %>
      <%# также, как мы делали циклы в ruby %>
      <% @questions.each do |question| %>
          <%# Мы рисуем здесь для кажого вопроса в списке вопросов фрагмент %>
          <%# (паршал), передавая в него текущий вопрос. Это очень похоже на %>
          <%# вызов метода в ruby %>
          <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>