config/routes.rb
Rails.application.routes.draw do
  # Это правило говорит: если пользователь заходит по адресу /, направь его в
  # контроллер users, действие index. Грубо говоря, на главной странице у нас
  # список юзеров.
  root 'users#index'

  # Ресурс пользователей
  resources :users

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  # Ресурс сессии (только три экшена :new, :create, :destroy)
  resource :session, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<%# Это общий шаблон для всех страниц нашего сайта. В него будут завернуты %>
<%# страницы нашего приложения. Здесь мы пропишем основную структуру наших %>
<%# html-страниц и укажем, куда вставлять шаблон отдельной вьюхи. %>
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
    <div class="header-nav">
      <!-- Если есть текущий юзер (значит он залогинен) -->
      <% if current_user %>
          <!-- Даем ссылки на его профиль и на логаут -->
          <%= link_to "@#{current_user.username}", user_path(current_user) %> |
          <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
          <!-- Если нету - ссылки на регистрацию и логин -->
          <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
          <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <%# Выводим сообщение об ошибке или уведомление для пользователя. %>
    <%# Если в объеккте flash есть что-то, выводим содержимое на страницу, %>
    <%# если нет, игнорируем этот блок. %>
    <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
          <% end %>
        </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>